# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 8
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk_8_2_1
from isi_sdk_8_2_1.models.cloud_settings_settings_cloud_policy_defaults_cache import CloudSettingsSettingsCloudPolicyDefaultsCache  # noqa: E501
from isi_sdk_8_2_1.rest import ApiException


class TestCloudSettingsSettingsCloudPolicyDefaultsCache(unittest.TestCase):
    """CloudSettingsSettingsCloudPolicyDefaultsCache unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloudSettingsSettingsCloudPolicyDefaultsCache(self):
        """Test CloudSettingsSettingsCloudPolicyDefaultsCache"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk_8_2_1.models.cloud_settings_settings_cloud_policy_defaults_cache.CloudSettingsSettingsCloudPolicyDefaultsCache()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
