# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 4
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk_8_0_1
from isi_sdk_8_0_1.models.filepool_template import FilepoolTemplate  # noqa: E501
from isi_sdk_8_0_1.rest import ApiException


class TestFilepoolTemplate(unittest.TestCase):
    """FilepoolTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilepoolTemplate(self):
        """Test FilepoolTemplate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk_8_0_1.models.filepool_template.FilepoolTemplate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
