# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 8
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk_8_2_1
from isi_sdk_8_2_1.models.auth_role_create_params import AuthRoleCreateParams  # noqa: E501
from isi_sdk_8_2_1.rest import ApiException


class TestAuthRoleCreateParams(unittest.TestCase):
    """AuthRoleCreateParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthRoleCreateParams(self):
        """Test AuthRoleCreateParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk_8_2_1.models.auth_role_create_params.AuthRoleCreateParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
