# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 3
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk_8_0
from isi_sdk_8_0.models.snapshot_snapshots_summary_summary import SnapshotSnapshotsSummarySummary  # noqa: E501
from isi_sdk_8_0.rest import ApiException


class TestSnapshotSnapshotsSummarySummary(unittest.TestCase):
    """SnapshotSnapshotsSummarySummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSnapshotSnapshotsSummarySummary(self):
        """Test SnapshotSnapshotsSummarySummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk_8_0.models.snapshot_snapshots_summary_summary.SnapshotSnapshotsSummarySummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
