# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 6
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk_8_1_1
from isi_sdk_8_1_1.models.ndmp_session_extended import NdmpSessionExtended  # noqa: E501
from isi_sdk_8_1_1.rest import ApiException


class TestNdmpSessionExtended(unittest.TestCase):
    """NdmpSessionExtended unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNdmpSessionExtended(self):
        """Test NdmpSessionExtended"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk_8_1_1.models.ndmp_session_extended.NdmpSessionExtended()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
