# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 8
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk_8_2_1
from isi_sdk_8_2_1.models.settings_reporting_eula_item import SettingsReportingEulaItem  # noqa: E501
from isi_sdk_8_2_1.rest import ApiException


class TestSettingsReportingEulaItem(unittest.TestCase):
    """SettingsReportingEulaItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSettingsReportingEulaItem(self):
        """Test SettingsReportingEulaItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk_8_2_1.models.settings_reporting_eula_item.SettingsReportingEulaItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
