# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 2
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk_7_2
from isi_sdk_7_2.models.nfs_aliases_extended import NfsAliasesExtended  # noqa: E501
from isi_sdk_7_2.rest import ApiException


class TestNfsAliasesExtended(unittest.TestCase):
    """NfsAliasesExtended unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNfsAliasesExtended(self):
        """Test NfsAliasesExtended"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk_7_2.models.nfs_aliases_extended.NfsAliasesExtended()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
