# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 8
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk_8_2_1
from isi_sdk_8_2_1.models.worm_domain import WormDomain  # noqa: E501
from isi_sdk_8_2_1.rest import ApiException


class TestWormDomain(unittest.TestCase):
    """WormDomain unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWormDomain(self):
        """Test WormDomain"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk_8_2_1.models.worm_domain.WormDomain()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
