# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 8
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk_8_2_1
from isi_sdk_8_2_1.models.histogram_stat_by import HistogramStatBy  # noqa: E501
from isi_sdk_8_2_1.rest import ApiException


class TestHistogramStatBy(unittest.TestCase):
    """HistogramStatBy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHistogramStatBy(self):
        """Test HistogramStatBy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk_8_2_1.models.histogram_stat_by.HistogramStatBy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
