# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 8
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk_8_2_1
from isi_sdk_8_2_1.models.audit_topic import AuditTopic  # noqa: E501
from isi_sdk_8_2_1.rest import ApiException


class TestAuditTopic(unittest.TestCase):
    """AuditTopic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuditTopic(self):
        """Test AuditTopic"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk_8_2_1.models.audit_topic.AuditTopic()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
