# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 8
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class StoragepoolSuggestedProtection(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'suggested_protection': 'str'
    }

    attribute_map = {
        'suggested_protection': 'suggested_protection'
    }

    def __init__(self, suggested_protection=None):  # noqa: E501
        """StoragepoolSuggestedProtection - a model defined in Swagger"""  # noqa: E501

        self._suggested_protection = None
        self.discriminator = None

        if suggested_protection is not None:
            self.suggested_protection = suggested_protection

    @property
    def suggested_protection(self):
        """Gets the suggested_protection of this StoragepoolSuggestedProtection.  # noqa: E501

        The suggested protection policy.  # noqa: E501

        :return: The suggested_protection of this StoragepoolSuggestedProtection.  # noqa: E501
        :rtype: str
        """
        return self._suggested_protection

    @suggested_protection.setter
    def suggested_protection(self, suggested_protection):
        """Sets the suggested_protection of this StoragepoolSuggestedProtection.

        The suggested protection policy.  # noqa: E501

        :param suggested_protection: The suggested_protection of this StoragepoolSuggestedProtection.  # noqa: E501
        :type: str
        """

        self._suggested_protection = suggested_protection

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StoragepoolSuggestedProtection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
