# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 5
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk_8_1_0
from isi_sdk_8_1_0.models.snapshot_lock import SnapshotLock  # noqa: E501
from isi_sdk_8_1_0.rest import ApiException


class TestSnapshotLock(unittest.TestCase):
    """SnapshotLock unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSnapshotLock(self):
        """Test SnapshotLock"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk_8_1_0.models.snapshot_lock.SnapshotLock()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
