# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 8
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CompatibilitiesSsdActiveActiveItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'class_1': 'str',
        'count': 'bool',
        'id': 'int'
    }

    attribute_map = {
        'class_1': 'class_1',
        'count': 'count',
        'id': 'id'
    }

    def __init__(self, class_1=None, count=None, id=None):  # noqa: E501
        """CompatibilitiesSsdActiveActiveItem - a model defined in Swagger"""  # noqa: E501

        self._class_1 = None
        self._count = None
        self._id = None
        self.discriminator = None

        self.class_1 = class_1
        self.count = count
        self.id = id

    @property
    def class_1(self):
        """Gets the class_1 of this CompatibilitiesSsdActiveActiveItem.  # noqa: E501

        The node class of an ssd compatibility  # noqa: E501

        :return: The class_1 of this CompatibilitiesSsdActiveActiveItem.  # noqa: E501
        :rtype: str
        """
        return self._class_1

    @class_1.setter
    def class_1(self, class_1):
        """Sets the class_1 of this CompatibilitiesSsdActiveActiveItem.

        The node class of an ssd compatibility  # noqa: E501

        :param class_1: The class_1 of this CompatibilitiesSsdActiveActiveItem.  # noqa: E501
        :type: str
        """
        if class_1 is None:
            raise ValueError("Invalid value for `class_1`, must not be `None`")  # noqa: E501

        self._class_1 = class_1

    @property
    def count(self):
        """Gets the count of this CompatibilitiesSsdActiveActiveItem.  # noqa: E501

        Is this SSD Compatibility Count Compatible.  # noqa: E501

        :return: The count of this CompatibilitiesSsdActiveActiveItem.  # noqa: E501
        :rtype: bool
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this CompatibilitiesSsdActiveActiveItem.

        Is this SSD Compatibility Count Compatible.  # noqa: E501

        :param count: The count of this CompatibilitiesSsdActiveActiveItem.  # noqa: E501
        :type: bool
        """
        if count is None:
            raise ValueError("Invalid value for `count`, must not be `None`")  # noqa: E501

        self._count = count

    @property
    def id(self):
        """Gets the id of this CompatibilitiesSsdActiveActiveItem.  # noqa: E501

        The id of this ssd compatibility  # noqa: E501

        :return: The id of this CompatibilitiesSsdActiveActiveItem.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CompatibilitiesSsdActiveActiveItem.

        The id of this ssd compatibility  # noqa: E501

        :param id: The id of this CompatibilitiesSsdActiveActiveItem.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CompatibilitiesSsdActiveActiveItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
