# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 8
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class NfsNetgroupSettings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bgwrite': 'int',
        'expiration': 'int',
        'lifetime': 'int',
        'retry': 'int'
    }

    attribute_map = {
        'bgwrite': 'bgwrite',
        'expiration': 'expiration',
        'lifetime': 'lifetime',
        'retry': 'retry'
    }

    def __init__(self, bgwrite=None, expiration=None, lifetime=None, retry=None):  # noqa: E501
        """NfsNetgroupSettings - a model defined in Swagger"""  # noqa: E501

        self._bgwrite = None
        self._expiration = None
        self._lifetime = None
        self._retry = None
        self.discriminator = None

        if bgwrite is not None:
            self.bgwrite = bgwrite
        if expiration is not None:
            self.expiration = expiration
        if lifetime is not None:
            self.lifetime = lifetime
        if retry is not None:
            self.retry = retry

    @property
    def bgwrite(self):
        """Gets the bgwrite of this NfsNetgroupSettings.  # noqa: E501

        To-disk backup interval for the netgroup cache.  # noqa: E501

        :return: The bgwrite of this NfsNetgroupSettings.  # noqa: E501
        :rtype: int
        """
        return self._bgwrite

    @bgwrite.setter
    def bgwrite(self, bgwrite):
        """Sets the bgwrite of this NfsNetgroupSettings.

        To-disk backup interval for the netgroup cache.  # noqa: E501

        :param bgwrite: The bgwrite of this NfsNetgroupSettings.  # noqa: E501
        :type: int
        """

        self._bgwrite = bgwrite

    @property
    def expiration(self):
        """Gets the expiration of this NfsNetgroupSettings.  # noqa: E501

        Time between updates of netgroups in the cache.  # noqa: E501

        :return: The expiration of this NfsNetgroupSettings.  # noqa: E501
        :rtype: int
        """
        return self._expiration

    @expiration.setter
    def expiration(self, expiration):
        """Sets the expiration of this NfsNetgroupSettings.

        Time between updates of netgroups in the cache.  # noqa: E501

        :param expiration: The expiration of this NfsNetgroupSettings.  # noqa: E501
        :type: int
        """

        self._expiration = expiration

    @property
    def lifetime(self):
        """Gets the lifetime of this NfsNetgroupSettings.  # noqa: E501

        Length of time an un-accessed netgroup remains in the cache.  # noqa: E501

        :return: The lifetime of this NfsNetgroupSettings.  # noqa: E501
        :rtype: int
        """
        return self._lifetime

    @lifetime.setter
    def lifetime(self, lifetime):
        """Sets the lifetime of this NfsNetgroupSettings.

        Length of time an un-accessed netgroup remains in the cache.  # noqa: E501

        :param lifetime: The lifetime of this NfsNetgroupSettings.  # noqa: E501
        :type: int
        """

        self._lifetime = lifetime

    @property
    def retry(self):
        """Gets the retry of this NfsNetgroupSettings.  # noqa: E501

        Retry interval for netgroup updates if the remote provider is unresponsive.  # noqa: E501

        :return: The retry of this NfsNetgroupSettings.  # noqa: E501
        :rtype: int
        """
        return self._retry

    @retry.setter
    def retry(self, retry):
        """Sets the retry of this NfsNetgroupSettings.

        Retry interval for netgroup updates if the remote provider is unresponsive.  # noqa: E501

        :param retry: The retry of this NfsNetgroupSettings.  # noqa: E501
        :type: int
        """

        self._retry = retry

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NfsNetgroupSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
