# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 7
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk_8_2_0
from isi_sdk_8_2_0.models.node_state_readonly import NodeStateReadonly  # noqa: E501
from isi_sdk_8_2_0.rest import ApiException


class TestNodeStateReadonly(unittest.TestCase):
    """NodeStateReadonly unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNodeStateReadonly(self):
        """Test NodeStateReadonly"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk_8_2_0.models.node_state_readonly.NodeStateReadonly()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
